language: go
go:
  - 1.15.x
os:
  - linux
  - osx
sudo: true
script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - i@sjis.me
    on_success: always
    on_failure: always